language: ruby
rvm:
- 2.6.4
before_install:
- gem install bundler
services:
- postgresql
before_script:
- cp config/database.yml.ci config/database.yml
- psql -c 'create database travis_ci_test;' -U postgres
script:
- bundle exec rails db:migrate RAILS_ENV=test
#- bundle exec rspec
